### ISSUE TITLE
Feedback for “Install”

### ISSUE THREAD

**Issue by virgilbourassa** [Dashlane/dashlane-cli#213] opened 2024-02-09 23:22 UTC
After installing on mac os with homebrew, I get:

% dcli                                 
node:internal/bootstrap/realm:420
  if (!mod) throw new TypeError(`Missing internal module '${id}'`);
            ^

TypeError: Missing internal module 'internal/modules/cjs/helpers'
    at requireBuiltin (node:internal/bootstrap/realm:420:19)
    at pkg/prelude/bootstrap.js:1884:12
    at pkg/prelude/bootstrap.js:1986:3
    at pkg/prelude/bootstrap.js:2259:3
    at readPrelude (node:internal/bootstrap/pkg:36:12)
    at node:internal/bootstrap/pkg:41:18
    at node:internal/bootstrap/pkg:48:4
    at node:internal/bootstrap/pkg:49:2

Node.js v18.19.0
---- How should I fix this?

**Comment by Mikescops** [comment] 2024-02-09 23:46
Duplicate of #211. Follow the other issue please, thanks!

**Closed** 2024-02-09 23:46 UTC
