### ISSUE TITLE
Not working on macOS since update

### ISSUE THREAD

**Issue by Spratch** [Dashlane/dashlane-cli#211] opened 2024-02-09 10:08 UTC
**Describe the bug**
I've updated dcli with brew on 2 macbook and since this update dcli is not working. 
Here what I have if I try to run dcli:

dcli
node:internal/bootstrap/realm:420
  if (!mod) throw new TypeError(`Missing internal module '${id}'`);
            ^

TypeError: Missing internal module 'internal/modules/cjs/helpers'
    at requireBuiltin (node:internal/bootstrap/realm:420:19)
    at pkg/prelude/bootstrap.js:1884:12
    at pkg/prelude/bootstrap.js:1986:3
    at pkg/prelude/bootstrap.js:2259:3
    at readPrelude (node:internal/bootstrap/pkg:36:12)
    at node:internal/bootstrap/pkg:41:18
    at node:internal/bootstrap/pkg:48:4
    at node:internal/bootstrap/pkg:49:2

Node.js v18.19.0

**To Reproduce**
1. Open terminal
2. Run brew install dashlane/tap/dashlane-cli (no error)
4. Run dcli or dcli sync
5. See error

**Expected behavior**
I excepted the program to run and sync.

**Environment (please complete the following information):**
MacOS Sonoma 14.3.1
Apple M1, and Apple M3

**Comment by Mikescops** [comment] 2024-02-09 10:32
Hello,

Thanks for reporting this issue, on one of your Mac can you `dcli logout`. I'd like to confirm if it's an issue related to updating from an older version or not.

I can't reproduce this on my Mac M1, but I'll keep investigating.

**Comment by Spratch** [comment] 2024-02-09 10:35
I can't, I have the same error message

**Comment by tmwrnr** [comment] 2024-02-10 06:18
I have the same issue. After the update from 1.15.2 to 6.2405.0 I only get the mentioned error message. 

Environment (please complete the following information):
MacOS Sonoma 14.3.1
Macbook Pro 2020 (Intel)

**Comment by tmwrnr** [comment] 2024-02-10 06:32
@Spratch Until this error is resolved you can download the binary from the release page ([v1.15.2](https://github.com/Dashlane/dashlane-cli/releases/tag/v1.15.2)). This version is still working for me.

**Comment by Mikescops** [comment] 2024-02-10 09:45
Hello @Spratch and @tmwrnr, I found that the issue is coming from a minor update in our executable bundler.

I pushed a fix but in order for you to get the correct version you need to run the following commands:
```
brew uninstall dashlane/tap/dashlane-cli
brew cleanup dashlane/tap/dashlane-cli
brew untap dashlane/tap
brew tap dashlane/tap
brew install dashlane/tap/dashlane-cli
```

This will ensure that any cached Formula is removed so you get my latest changes on the formula. (https://github.com/Dashlane/homebrew-tap/commit/226e7ef03b427df00b53f0bd747d5f049a680225)

**Comment by tmwrnr** [comment] 2024-02-11 07:13
@Mikescops Thanks, now everything works again for me with the latest version 👍

**Closed** 2024-02-11 07:36 UTC
Labels: bug
